ES = 1  # enlarge_scale: 分存图放大倍数
TARGET = r"/data/django/mysite_git/VisualWallet-backend/mysite/qr/kn/imgs/test.png"
CARRIERPATH = r"/data/django/mysite_git/VisualWallet-backend/mysite/qr/kn/imgs/carrier"
KEYPATH = r"/data/django/mysite_git/VisualWallet-backend/mysite/qr/kn/imgs/key"
RETSPLITPATH = r"/data/django/mysite_git/VisualWallet-backend/mysite/qr/kn/imgs/ret"
ADDRESS = r"/data/django/mysite_git/VisualWallet-backend/mysite/qr/kn/imgs/"
BTCLOGO = r"/data/django/mysite_git/VisualWallet-backend/mysite/qr/kn/imgs/template/btc.png"
ETHLOGO = r"/data/django/mysite_git/VisualWallet-backend/mysite/qr/kn/imgs/template/eth.png"
ETHDOTLOGO = r"/data/django/mysite_git/VisualWallet-backend/mysite/qr/kn/imgs/template/eth_dot.png"
