/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_visualwallet_cpplib_CppLib */

#ifndef _Included_com_visualwallet_cpplib_CppLib
#define _Included_com_visualwallet_cpplib_CppLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_visualwallet_cpplib_CppLib
 * Method:    detect
 * Signature: ([BII[[I[[III[[II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_visualwallet_cpplib_CppLib_detect
  (JNIEnv *, jclass, jbyteArray, jint, jint, jobjectArray, jobjectArray, jint, jint, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
