# Generated by Django 3.1.8 on 2021-04-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretKeyHash', models.CharField(max_length=512)),
                ('coeK', models.IntegerField()),
                ('coeN', models.IntegerField()),
                ('carry0', models.TextField()),
                ('carry1', models.TextField(blank=True)),
                ('carry2', models.TextField(blank=True)),
                ('carry3', models.TextField(blank=True)),
                ('carry4', models.TextField(blank=True)),
                ('length', models.IntegerField()),
                ('c1', models.IntegerField()),
                ('c2', models.IntegerField()),
                ('c3', models.IntegerField()),
            ],
        ),
    ]
