# Generated by Django 3.1.8 on 2021-04-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinfo',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
