# Generated by Django 3.1.8 on 2021-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_skinfo_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinfo',
            name='carry0',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='skinfo',
            name='carry1',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='skinfo',
            name='carry2',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='skinfo',
            name='carry3',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='skinfo',
            name='carry4',
            field=models.BinaryField(blank=True),
        ),
    ]
