# Generated by Django 3.1.8 on 2021-05-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_auto_20210427_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinfo',
            name='hash0',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skinfo',
            name='hash1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skinfo',
            name='hash2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skinfo',
            name='hash3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skinfo',
            name='hash4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
