# Generated by Django 3.2.5 on 2021-07-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_auto_20210723_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinfo',
            name='fixed',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
